# Generated by Django 5.2.8 on 2025-12-07 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistas', '0002_practica_imagen_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practica',
            name='imagen_url',
        ),
        migrations.AddField(
            model_name='practica',
            name='email',
            field=models.EmailField(default='', max_length=150),
        ),
    ]
