# Generated by Django 5.2.8 on 2025-12-11 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistas', '0003_remove_practica_imagen_url_practica_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('personajes', models.CharField(blank=True, max_length=500)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('etiquetas', models.CharField(blank=True, max_length=500)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='obras/')),
                ('contenido', models.TextField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vistas.practica')),
            ],
        ),
    ]
