# Generated by Django 5.2.8 on 2025-12-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistas', '0004_obra'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='imagen_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
